### ISSUE TITLE
Modify Create Fantasy Team Endpoint

### ISSUE THREAD

**Issue by kisakyegordon** [arthuroe/fp#32]
- At the moment, when you just put in only a name to the endpoint - its shows a successful add but its not stored in the DB
`POST : http://localhost:5000/api/v1/fantasy_teams`
- Also one user can create  more than one fantasy team - which shouldn't be the case.
- A user should also have the ability to update their fantasy team name.

**Comment by arthuroe** [comment]
> At the moment, when you just put in only a name to the endpoint - its shows a successful add but its not stored in the DB

@kisakyegordon that's the bug I talked about earlier when adding a fantasy team. I addressed that issue in PR #23

> Also one user can create more than one fantasy team - which shouldn't be the case.
> A user should also have the ability to update their fantasy team name.

Will include these changes in that PR.

**Comment by kisakyegordon** [comment]
@arthuroe Just raised some issues on this PR - if you can get most of the items worked on - it will allow to make front-end updates on the weekend aswell before the new week drama kicks in. 💪🏾
