### ISSUE TITLE
Add Jersey's to the Backend

### ISSUE THREAD

**Issue by kisakyegordon** [arthuroe/fp#33]
- We need to add team jersey entries to the backend - am not sure how you will pull it off but feel free to pass it by me incase you need any extra info on this.

**Comment by arthuroe** [comment]
@kisakyegordon Are the jerseys linked to a player?
I can add the jersey to the team and then include an attribute for team jersey to the player response. The attribute will not be stored along with the player attributes in the DB but rather picked from the team attributes stored in the DB given the tables are connected.

**Comment by kisakyegordon** [comment]
@arthuroe This same jersey approach is going to apply to team logo's aswell.
- Kindly cater for them aswell when you get to work on it, theres are some samples you can download form the mockups.

**Comment by serubirikenny** [comment]
Gordon what do you mean Team logo?

**Comment by kisakyegordon** [comment]
@serubirikenny Like the team crest, like Arsenals gunners badge.
Its displayed on the fixtures page.

**Comment by serubirikenny** [comment]
Ooh cool ...cool

**Comment by arthuroe** [comment]
@kisakyegordon do you mean adding the team logo to the player response as well?
Logo is already an attribute on the team itself.

**Comment by serubirikenny** [comment]
player has no logo.... its the team ....on the fixtures page that has a logo

**Comment by kisakyegordon** [comment]
@arthuroe i meant applying the same storage approach that will be applied to jerseys - since they are both images.
