### ISSUE TITLE
Modify fantasy_team_created attribute

### ISSUE THREAD

**Issue by kisakyegordon** [arthuroe/fp#45]
- Currently the `fantasy_team_created` attribute in the user table is set to `true` when a user gives his team a `name` but before he adds any players to his team.

1 -  I have a `TransferList` page that aims to check if a user has a team or not before it redirects them inside the app - with the current setup, after a user has setup a `team name` the app assumes they have `finished` creating a fantasy team which  is not entirely true, which makes the user get redirected into the app pre-maturely.

- Is it possible to modify the `GET /current_user` to check if the `user's team_id` has any records in the `fantasy_teams` table - then return a `false` if there is no entry or a `true` is there is an entry -  that way a user is `only` redirected into the app after theyve `selected a squad`

2 - Also could is it possible to modify the `current_user` returned body to include the users `team_id` - it makes it easier for me to make queries about the users team that way.
      - I had made this change on dev to help me work locally
![Screen Shot 2020-04-07 at 00 32 26](https://user-images.githubusercontent.com/8231705/78633599-a09f9900-7867-11ea-9dc0-cafd72503ecb.png)

**Comment by arthuroe** [comment]
@kisakyegordon there is an endpoint `fantasy_team_players/<team_id>` that returns a message `no players have been added` in case the fantasy team has no players. Is this enough?

The user model already has a reference to the fantasy team table so you do not need to make any queries there. `user.fantasy_team` returns the object.

The fantasy team_id can be added to the response.

**Comment by arthuroe** [comment]
> Is it possible to modify the GET /current_user to check if the user's team_id has any records in the fantasy_teams table - then return a false if there is no entry or a true is there is an entry - that way a user is only redirected into the app after theyve selected a squad

Let's say a user has added only a single entry of players in the team, does that still count as him having completed adding players to the team?

**Comment by kisakyegordon** [comment]
> > Is it possible to modify the GET /current_user to check if the user's team_id has any records in the fantasy_teams table - then return a false if there is no entry or a true is there is an entry - that way a user is only redirected into the app after theyve selected a squad
> 
> Let's say a user has added only a single entry of players in the team, does that still count as him having completed adding players to the team?

Yeah it kinda does count - since at the squad selection page - there will be rules that ensure the user selects all the players

**Comment by arthuroe** [comment]
> @kisakyegordon there is an endpoint fantasy_team_players/<team_id> that returns a message no players have been added in case the fantasy team has no players. Is this enough?

??

**Comment by kisakyegordon** [comment]
It can work for now

**Comment by arthuroe** [comment]
Added attribute for `fantasy_team_players_added` to current user.

**Comment by arthuroe** [comment]
@kisakyegordon going to merge and close this issue.
