### ISSUE TITLE
Expected My Team Query Response

### ISSUE THREAD

**Issue by kisakyegordon** [arthuroe/fp#58]
{
    "players": [
        {
            "age": 25,
            "availability": "false",
            "created_at": "Fri, 21 Feb 2020 00:00:00 GMT",
            "id": 6,
            "jersey": "https://res.cloudinary.com/ddhna2s9j/image/upload/v1587270269/green-yellow.png",
            "name": "Jouanny",
            "points": 98,
            "position": "WB",
            "price": 92,
            "team_id": 6,
            "updated_at": "Tue, 18 Feb 2020 00:00:00 GMT",
            "is_substitute": false,
            "is_captain": false,
            "is_vice": false
        },
        {
            "age": 24,
            "availability": "true",
            "created_at": "Sat, 21 Dec 2019 00:00:00 GMT",
            "id": 24,
            "jersey": "https://res.cloudinary.com/ddhna2s9j/image/upload/v1587270332/black-blue.png",
            "name": "Bartell",
            "points": 15,
            "position": "WB",
            "price": 28,
            "team_id": 4,
            "updated_at": "Sat, 26 Oct 2019 00:00:00 GMT",
            "is_substitute": false,
            "is_captain": false,
            "is_vice": false
        }
    ]
}

**Comment by arthuroe** [comment]
@kisakyegordon I don't think you got what I was saying. I was talking about the expected request you will send to the backend regarding the `starting 11`. Options are passing an array of starting players `id's`.

**Comment by kisakyegordon** [comment]
I probably didn't get it well .
We can have a sync sometime tomorrow probably around 10pm your time.
But for now seems like the array with player ids is the only option
