### ISSUE TITLE
Modify the way we pick the starting players

### ISSUE THREAD

**Issue by kisakyegordon** [arthuroe/fp#65]
- At the moment to `display` and `organize` the MyTeam Screen (where the subs happen) 2 endpoints need to be hit ie : 
   - `/fantasy_team_players/<fantasy_team_id>` & `/starting_players`.

Which means when i make a change in one it affects the other and i have to make a change on the aswell which i believe we can avoid if we can have one endpoint probably `/fantasy_team_players/<fantasy_team_id>` also include `[is_captain, is_vice, is_sub]` it would make it faster for the front-end to handle this.

Ps: For now this is mostly an issue with the `GET` the other associated  methods for both endpoints can remain as is unless we ever really need to change em

**Comment by arthuroe** [comment]
One post Method adds players to the team, the other saves team structure.

The only difference is the GET's having different attributes that can all be fitted into one endpoint.

I don't get the point where you making a change, affects the other given the GET's only retrieve data from the API.
@kisakyegordon

**Comment by arthuroe** [comment]
Let me work on unifying the GET's before EOD my side.

**Comment by kisakyegordon** [comment]
`I don't get the point where you making a change, affects the other given the GET's only retrieve data from the API.`

They only retrieve data - true - to display the the players info {name, position, jersey...} i need `/fantasy_team_players/<fantasy_team_id>` but to determine who gets displayed as a starter depends on `/starting_players` both kinda block making a sub .

Id rather just show you
